[package]
name = "contacts"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "contacts"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

contacts_integrity = { path = "../../integrity/contacts", package = "contacts_integrity" }
